spring.application.name=catering-system


spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/catering_system
spring.datasource.username=root
spring.datasource.password=123456

spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=GMT+8

mybatis.configuration.lazy-loading-enabled=true
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.nyw.cateringsystem.bean
mybatis.mapper-locations=classpath:/mapper/*.xml

logging.level.com.nyw.cateringsystem.repository=TRACE
logging.level.com.nyw.cateringsystem.converter=TRACE
logging.level.com.nyw.cateringsystem.service.impl.DishServiceImpl=TRACE

#spring.security.user.name=admin
#spring.security.user.password=$2a$10$Sxw/wNx6dwqgZbQ.TVhPCOi7uJUkSUA1K7NyQhKOmSiZsgNx6jUrW
#spring.security.user.roles=ADMIN
